version: '3'
services:
  app:
    build: .
    container_name: fruit_basket
    volumes:
      - ./:/home/fruit_basket
    ports:
      - "8030:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: mysql
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: fruit_basket
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123123

volumes:
  db_data: {}

