index:
   path: /
   controller: FruitBasket\Controller\UiController::index
eidt:
    path: /edit/{id}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /
        permanent: true
